
-- This View is Created to pull information from MIS and it associated entity

CREATE OR REPLACE VIEW MIS_VW AS 
SELECT M.ID, M.AGEING, M.BROKER, M.DEPT_NAME, M.DT_OF_FSR, 
M.DT_OF_ILA, M.DT_OF_LOR, M.DATE_OF_LOSS, M.DT_OF_SURVEY, 
M.DT_TIME_INTIMATION, M.EST_CLAIM_AMT, M.FIELD_STAFF, M.FSR_TAT, M.GR_DATE, M.GR_NO, M.ILA_TAT, 
M.INSURED, M.INSURER, 
M.INSURER_CLAIM_NO, M.INVOICE_DT, M.INVOICE_NO, M.JOB_NO, M.LAST_COMM_DATE, M.LOCATION_OF_LOSS, 
M.LOSS_RESERVE, M.MAIL_SEND_TO_BRANCH, M.POLICY_NO, M.REG_BRANCH, M.REG_DT, M.REP_NAME, M.REVISED_LOSS_RESERVE, 
M.SPECIAL_INFO, M.SRC_OF_INST, M.STATUS, M.SUB_DEPT, M.SURVEYOR, M.UPLOAD_FILE, 
B.ID AS BROKER_ID, B.NAME AS BROKER_NAME,
DEP.ID AS DEPARTMENT__ID, DEP.DESCRIPTION AS DEPARTMENT_DESC, DEP.NAME AS DEPARTMENT_NAME, DEP.TYPE AS DEPARTMENT_TYPE,
SDEP.ID AS SUB_DEP_ID, SDEP.DESCRIPTION AS SUB_DEP_DESC, SDEP.NAME AS SUB_DEP_NAME, SDEP.TYPE AS SUB_DEP_TYPE, 
FS.ID AS FIELD_STAFF_ID, 
FS.EMAIL AS FIELD_STAFF_EMAIL, FS.EMPLOYEE AS FIELD_STAFF_EMP, FS.MOBILE AS FIELD_STAFF_MOBILE, FS.NAME AS FIELD_STAFF_NAME, 
INRD.ID AS INSURED_ID, INRD.ADD_ON_POLICY_DOC AS INSURED_ADD_ON_POLICY_DOC, 
INRD.CITY AS INSURED_CITY, INRD.COUNTRY AS INSURED_COUNTRY, INRD.EMAIL AS INSURED_EMAIL, 
INRD.MOBILE AS INSURED_MOBILE, INRD.NAME AS INSURED_NAME, INRD.PINCODE AS INSURED_PINCODE, INRD.STATE AS INSURED_STATE,

INER.ID AS INSURER_ID, INER.GST_NO AS INSURER_GST_NO, INER.NAME AS INSURER_NAME, INER.STATE AS INSURER_STATE, INER.TYPE AS INSURER_TYPE, 

ECA.ID AS ESTIMATED_CLAIM_AMT_ID, ECA.VALUE AS ESTIMATED_CLAIM_AMT_VALUE ,
RB.ID AS REGISTRATION_BRANCH_ID, RB.NAME AS REGISTRATION_BRANCH_NAME,
SUR.ID AS SURVEYOR_ID, SUR.EMAIL AS SURVEYOR_EMAIL, SUR.EMPLOYEE AS SURVEYOR_EMPLOYEE, SUR.MOBILE AS SURVEYOR_MOBILE, 
SUR.NAME AS SURVEYOR_NAME,

SOI.ID AS SOURCE_OF_INSTRUCTION_ID, SOI.ADDRESS AS SOURCE_OF_INSTRUCTION_ADDRESS, SOI.CITY AS SOURCE_OF_INSTRUCTION_CITY, 
SOI.CONTACT_NO AS SOURCE_OF_INSTRUCTION_CONTACT_NO, 
SOI.EMAIL AS SOURCE_OF_INSTRUCTION_EMAIL, SOI.INSURER AS SOURCE_OF_INSTRUCTION_INSURER, 
SOI.NAME AS SOURCE_OF_INSTRUCTION_NAME, SOI.OFFICE_CODE_RO_DO AS SOURCE_OF_INSTRUCTION_OFFICE_CODE_RO_DO, 
SOI.PINCODE AS OFFICE_CODE_RO_DO_PINCODE 


FROM MIS M 
INNER JOIN BROKER B ON B.ID=M.BROKER
INNER JOIN DEPARTMENT DEP ON DEP.ID=M.DEPT_NAME
INNER JOIN SUB_DEPT SDEP ON SDEP.DEPARTMENT = DEP.ID AND SDEP.ID=M.SUB_DEPT
INNER JOIN FIELD_STAFF FS ON FS.ID=M.FIELD_STAFF
INNER JOIN INSURED INRD ON INRD.ID= M.INSURED
INNER JOIN INSURER INER ON INER.ID=M.INSURER
INNER JOIN ESTIMATED_CLAIM_AMT ECA ON ECA.ID=M.EST_CLAIM_AMT
INNER JOIN REGISTRATION_BRANCH RB ON RB.ID = M.REG_BRANCH
INNER JOIN SURVEYOR SUR  ON SUR.ID = M.SURVEYOR
INNER JOIN SOURCE_OF_INSTRUCTION SOI  ON SOI.ID=M.SRC_OF_INST;




